import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  DEFAULT_BLENDER_CODE,
  DEFAULT_SCENE_CODE,
  parseTunables,
  patchParam,
  type RenderSettings,
} from '@motionforge/shared';
import * as api from '../api/client';

/**
 * All editor state in one hook: the two generated code documents (source of
 * truth), the tunables parsed from the scene code, and the async actions
 * (generate/modify, exports, Blender sync/agent).
 */

export interface Status {
  kind: 'info' | 'error';
  text: string;
}

export interface Mp4JobState {
  id: string;
  status: 'running' | 'done' | 'error';
  progress: number;
  message: string;
  url?: string;
  error?: string;
}

export function useSceneProject() {
  const [code, setCode] = useState(DEFAULT_SCENE_CODE);
  const [blenderCode, setBlenderCode] = useState(DEFAULT_BLENDER_CODE);
  const [busy, setBusy] = useState<string | null>(null);
  const [status, setStatus] = useState<Status | null>(null);
  const [mp4Job, setMp4Job] = useState<Mp4JobState | null>(null);
  const [blenderStatus, setBlenderStatus] = useState<api.BlenderStatus | null>(null);
  const pollRef = useRef<number | null>(null);

  const tunables = useMemo(() => {
    try {
      return parseTunables(code);
    } catch {
      return [];
    }
  }, [code]);

  useEffect(() => {
    api.getBlenderStatus().then(setBlenderStatus).catch(() => setBlenderStatus(null));
  }, []);

  useEffect(
    () => () => {
      if (pollRef.current !== null) window.clearInterval(pollRef.current);
    },
    [],
  );

  const run = useCallback(async (label: string, fn: () => Promise<void>) => {
    setBusy(label);
    setStatus(null);
    try {
      await fn();
    } catch (err) {
      setStatus({ kind: 'error', text: err instanceof Error ? err.message : String(err) });
    } finally {
      setBusy(null);
    }
  }, []);

  const generate = useCallback(
    (prompt: string) =>
      run('Generating scene…', async () => {
        const result = await api.generate(prompt);
        setCode(result.code);
        if (result.blenderCode) setBlenderCode(result.blenderCode);
        setStatus({
          kind: 'info',
          text:
            result.source === 'template'
              ? 'Generated with the offline template (set OPENROUTER_API_KEY for AI generation).'
              : 'Scene generated by the AI agent.',
        });
      }),
    [run],
  );

  const modify = useCallback(
    (prompt: string) =>
      run('Modifying scene…', async () => {
        const result = await api.modify(prompt, code, blenderCode);
        setCode(result.code);
        if (result.blenderCode) setBlenderCode(result.blenderCode);
        setStatus({ kind: 'info', text: 'Scene modified by the AI agent.' });
      }),
    [run, code, blenderCode],
  );

  // Slider/switch changes are code edits: patch the PARAMS literal in place.
  const setParam = useCallback((name: string, value: number | boolean | string) => {
    setCode((current) => patchParam(current, name, value));
  }, []);

  const exportCode = useCallback(
    () =>
      run('Exporting code…', async () => {
        const blob = await api.exportCodeZip(code, blenderCode);
        downloadBlob(blob, 'motionforge-scene.zip');
        setStatus({ kind: 'info', text: 'Project exported as motionforge-scene.zip.' });
      }),
    [run, code, blenderCode],
  );

  const exportMp4 = useCallback(
    (settings: RenderSettings) =>
      run('Starting MP4 render…', async () => {
        const { jobId } = await api.startMp4Export(code, settings);
        setMp4Job({ id: jobId, status: 'running', progress: 0, message: 'Queued' });
        if (pollRef.current !== null) window.clearInterval(pollRef.current);
        pollRef.current = window.setInterval(async () => {
          try {
            const job = await api.getMp4Job(jobId);
            setMp4Job({
              id: jobId,
              status: job.status,
              progress: job.progress,
              message: job.message,
              url: job.result?.url,
              error: job.error,
            });
            if (job.status !== 'running' && pollRef.current !== null) {
              window.clearInterval(pollRef.current);
              pollRef.current = null;
            }
          } catch {
            // transient poll failure — keep polling
          }
        }, 2000);
      }),
    [run, code],
  );

  const syncBlender = useCallback(
    () =>
      run('Sending scene to Blender…', async () => {
        const result = await api.blenderSync(blenderCode);
        setStatus({ kind: 'info', text: `Blender: ${result.output || 'scene updated'}` });
      }),
    [run, blenderCode],
  );

  const runBlenderAgent = useCallback(
    (prompt: string) =>
      run('Blender agent working…', async () => {
        const result = await api.blenderAgent(prompt);
        setStatus({ kind: 'info', text: `Blender agent: ${result.finalText.slice(0, 300)}` });
      }),
    [run],
  );

  return {
    code,
    setCode,
    blenderCode,
    setBlenderCode,
    tunables,
    setParam,
    busy,
    status,
    mp4Job,
    blenderStatus,
    generate,
    modify,
    exportCode,
    exportMp4,
    syncBlender,
    runBlenderAgent,
  };
}

function downloadBlob(blob: Blob, name: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}
